#!/bin/sh

if ! getent group avahi >/dev/null 2>&1; then
    groupadd -g 84 avahi || exit 1
fi

if ! getent passwd avahi >/dev/null 2>&1; then
    useradd \
        -r \
        -u 84 \
        -g avahi \
        -d /run/avahi-daemon \
        -s /bin/false \
        -M \
        -c "Avahi Daemon Owner" \
        avahi || exit 1
fi

if ! getent group netdev >/dev/null 2>&1; then
    groupadd -g 86 netdev || exit 1
fi

exit 0
