#!/bin/sh
install -dvm 755 /usr/lib/cups/backend &&
ln -v -sf /usr/bin/smbspool /usr/lib/cups/backend/smb
cat > /etc/samba/smb.conf  << "EOF"
[global]
    workgroup = WORKGROUP
    dos charset = cp850
    unix charset = ISO-8859-1
EOF
