#!/bin/sh

if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
    systemctl daemon-reload

    systemctl preset \
        virtqemud.socket \
        virtlogd.socket \
        virtlockd.socket \
        virtnetworkd.socket \
        virtstoraged.socket \
        virtnodedevd.socket \
        virtnwfilterd.socket \
        virtsecretd.socket

    systemctl start \
        virtqemud.socket \
        virtlogd.socket \
        virtlockd.socket \
        virtnetworkd.socket \
        virtstoraged.socket \
        virtnodedevd.socket \
        virtnwfilterd.socket \
        virtsecretd.socket
fi

exit 0
